# Generated by Django 3.2.3 on 2021-10-21 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms_app', '0004_auto_20211021_1819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='desc',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
